[package]
name = "polonius"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.7.0"
eyre = "0.6.5"
itertools = "0.10"

# Graphviz
glob = "0.3"
html-escape = "0.2"